name: spectrio-web-app

on:
  push:
    branches:
      - main  
      - dev
      - staging

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT_STAGE: ${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/staging' && 'staging') || 'dev' }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/main' && 'production') || (github.ref == 'refs/heads/staging' && 'staging') || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          role-session-name: githubactionssession
          aws-region: "us-east-1"

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set image variables
        run: |
          echo "REGISTRY=${{ steps.ecr-login.outputs.registry }}" >> $GITHUB_ENV
          echo "REPOSITORY=spectrio-web-app" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build, tag, and push Docker image to Amazon ECR
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Debug Environment Variables
        run: |
          echo "Registry: $REGISTRY"
          echo "Repository: $REPOSITORY"
          echo "Image Tag: $IMAGE_TAG"

      - name: Login to EKS - update kubeconfig
        run: |
          aws eks update-kubeconfig --name spectrio-cluster-dev --region us-east-1

      - name: Replace image placeholder
        run: |
          sed -i "s|PLACEHOLDER_IMAGE|$REGISTRY/$REPOSITORY:$IMAGE_TAG|g" ./deployment.yaml

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./deployment.yaml
          kubectl apply -f ./service.yaml
          kubectl apply -f ./ingress.yaml

# Podinfo web app

      - name: Apply Podinfo Deployment
        run: |
          kubectl apply -f ./podinfo-app/podinfo-deployment.yaml

      - name: Apply Podinfo Service
        run: |
          kubectl apply -f ./podinfo-app/podinfo-service.yaml

      - name: Apply Horizontal Pod Autoscaler
        run: |
          kubectl apply -f ./podinfo-app/podinfo-hpa.yaml
